services:
  digitalizate-frontend:
    build: .
    container_name: digitalizate-frontend
    expose:
      - "3000"
    env_file: .env
    environment:
      - PORT=3000
      - HOSTNAME=0.0.0.0
    restart: unless-stopped
    networks:
      - proxy-network

  digitalizate-api:
    build: ./backend
    container_name: digitalizate-api
    expose:
      - "3031"
    env_file: ./backend/.env
    restart: unless-stopped
    networks:
      - proxy-network
      - digitalizate-db

networks:
  proxy-network:
    external: true
  digitalizate-db:
    external: true
